// Single source of truth for all pieces.
// To publish a piece: make sure pieces/{id}/index.html exists.
window.PIECES = [
  {
    id: 'seesaw-volume',
    title: 'Seesaw Volume',
    sin: 'Tilt the slider and let gravity roll the value around',
    dateAdded: '2026-06-03',
    credit: 'welchj',
  },
  {
    id: 'cursor-decoys',
    title: 'Cursor Decoys',
    sin: 'Every click hides your cursor among more identical decoys',
    dateAdded: '2026-06-03',
    credit: 'welchj',
  },
  {
    id: 'wind-blow',
    title: 'Wind Blow',
    sin: 'Fan blows cursor away from the Unsubscribe button',
    dateAdded: '2026-06-03',
    credit: 'welchj',
  },
  {
    id: 'password-hints',
    title: 'Helpful Password',
    sin: 'Reveals which characters are correct position by position',
    dateAdded: '2026-06-03',
    credit: 'welchj',
  },
  {
    id: 'slippery-yes',
    title: 'Slippery Yes',
    sin: 'Confirmation button swaps places whenever you hover over it',
    dateAdded: '2026-06-03',
    credit: 'welchj',
  },
  {
    id: 'scattered-keyboard',
    title: 'Scattered Keyboard',
    sin: 'Navigate randomly scattered keys with arrow keys to type anything',
    dateAdded: '2026-06-03',
    credit: 'Reddit',
  },
  {
    id: 'fan-cursor',
    title: 'Fan Cursor Keyboard',
    sin: "You can't click keys — you aim a physics fan at them",
    dateAdded: '2026-06-02',
    credit: 'themutti',
  },
  {
    id: 'birthday-highlow',
    title: 'Birthday High-Low',
    sin: 'Binary-searching for information you already know',
    dateAdded: '2026-06-02',
    credit: 'Nifty Octopus',
  },
  {
    id: 'unsubscribe-cursor',
    title: 'Unsubscribe',
    sin: "Custom cursor communicates contempt for the user's intent",
    dateAdded: '2026-06-02',
    credit: 'Reddit',
  },
  {
    id: 'etch-a-phone',
    title: 'Etch-a-Phone',
    sin: 'Gating a text field behind one-line handwriting OCR',
    dateAdded: '2026-05-20',
    credit: 'Reddit',
  },
  {
    id: 'random-phone',
    title: 'Random phone',
    sin: 'Replacing input with a slot machine',
    dateAdded: '2026-05-20',
    credit: 'Reddit',
  },
  {
    id: 'date-boomerang',
    title: 'Date Boomerang',
    sin: 'The date handle never holds still',
    dateAdded: '2026-05-20',
    credit: 'Reddit',
  },
  {
    id: 'date-slider',
    title: 'Date Slider',
    sin: 'Continuous control for a precise discrete value',
    dateAdded: '2026-05-10',
    credit: 'Reddit',
  },
  {
    id: 'phone-boomerang',
    title: 'Phone Boomerang',
    sin: 'Control refuses to hold its value',
    dateAdded: '2026-05-15',
    credit: 'Reddit',
  },
  {
    id: 'pump-volume',
    title: 'Pump It Volume!',
    sin: 'Absurd physical effort for a one-click control',
    dateAdded: '2026-05-01',
    credit: 'Reddit',
  },
];
