// Single source of truth for all pieces.
// To publish a piece: set status to 'live' and make sure
// pieces/{id}/index.html exists.
window.PIECES = [
  {
    id: 'pump-volume',
    title: 'Pump It Volume!',
    description: 'Raise the volume by manually pumping a bike pump. Drag the handle up and down. It leaks.',
    category: 'Interactions',
    tags: ['volume', 'pump', 'effort'],
    icon: 'air',
    status: 'live',
    sin: 'Absurd physical effort for a one-click control',
  },
  {
    id: 'erratic-slider',
    title: 'The Erratic Volume Slider',
    description: 'Drag right to go quieter. Drag left to go louder. Sometimes neither.',
    category: 'Interactions',
    tags: ['slider', 'audio', 'controls'],
    icon: 'volume_up',
    status: 'coming-soon',
    sin: 'Violates direct manipulation',
  },
  {
    id: 'moving-target',
    title: 'The Moving Target',
    description: 'The delete button sprints away from your cursor every time you hover.',
    category: 'Interactions',
    tags: ['button', 'hover', 'delete'],
    icon: 'ads_click',
    status: 'coming-soon',
    sin: "Fitt's Law violation",
  },
  {
    id: 'password-nightmare',
    title: 'Password Nightmare',
    description: "Requires 14 chars, 2 emojis, a prime number, and your firstborn's name.",
    category: 'Interactions',
    tags: ['form', 'password', 'validation'],
    icon: 'lock',
    status: 'coming-soon',
    sin: 'Hostile form design',
  },
  {
    id: 'confirm-loop',
    title: 'The Confirm Loop',
    description: 'Are you sure? Are you REALLY sure? 17 dialogs to delete one tiny file.',
    category: 'Interactions',
    tags: ['dialog', 'confirm', 'friction'],
    icon: 'help',
    status: 'coming-soon',
    sin: 'Alert fatigue',
  },
  {
    id: 'invisible-submit',
    title: 'Invisible Submit',
    description: "The submit button is white. The background is white. It's definitely there.",
    category: 'Dark Patterns',
    tags: ['button', 'visibility', 'contrast'],
    icon: 'visibility_off',
    status: 'coming-soon',
    sin: 'Hidden affordance',
  },
  {
    id: 'fake-progress',
    title: 'The Fake Progress Bar',
    description: 'Loads smoothly to 99%… then stops. Forever. The content was already rendered.',
    category: 'Dark Patterns',
    tags: ['loading', 'feedback', 'deception'],
    icon: 'hourglass_empty',
    status: 'coming-soon',
    sin: 'False feedback loop',
  },
  {
    id: 'cookie-wall',
    title: 'Cookie Wall of Doom',
    description: 'A GDPR consent modal covers the entire viewport. The dismiss X is 1×1 px.',
    category: 'Dark Patterns',
    tags: ['modal', 'gdpr', 'consent'],
    icon: 'cookie',
    status: 'coming-soon',
    sin: 'Hostile defaults',
  },
  {
    id: 'mandatory-account',
    title: 'Mandatory Account Checkout',
    description: 'You must create an account to check out. Creating an account clears your cart.',
    category: 'Dark Patterns',
    tags: ['checkout', 'auth', 'friction'],
    icon: 'shopping_cart',
    status: 'coming-soon',
    sin: 'Forced registration',
  },
  {
    id: 'font-lottery',
    title: 'Font Size Lottery',
    description: 'Every paragraph renders at a random font size between 4 px and 96 px on load.',
    category: 'Typography',
    tags: ['font', 'readability', 'size'],
    icon: 'text_fields',
    status: 'coming-soon',
    sin: 'Typographic chaos',
  },
  {
    id: 'low-contrast',
    title: 'Accessible™ Color Scheme',
    description: 'A carefully crafted palette with a 1.1:1 contrast ratio. WCAG-compliant, probably.',
    category: 'Color Horror',
    tags: ['contrast', 'accessibility', 'wcag'],
    icon: 'palette',
    status: 'coming-soon',
    sin: 'WCAG Level F',
  },
  {
    id: 'eternal-spinner',
    title: 'The Eternal Spinner',
    description: 'Loading… loading… The content was fully rendered on page load. Still loading.',
    category: 'Animation',
    tags: ['loading', 'spinner', 'ux'],
    icon: 'autorenew',
    status: 'coming-soon',
    sin: 'Phantom loading state',
  },
  {
    id: 'autocomplete-tyrant',
    title: 'Autocomplete Tyrant',
    description: 'Autocorrects "John" to "Johann Sebastian Bach." Every. Single. Time.',
    category: 'Interactions',
    tags: ['input', 'autocomplete', 'autocorrect'],
    icon: 'spellcheck',
    status: 'coming-soon',
    sin: 'Hostile automation',
  },
];
